### ISSUE TITLE
Build error when using ui-dropdown

### ISSUE THREAD

**Issue by kmmathis** [Semantic-Org/Semantic-UI-Ember#59]
I'm getting the following build error when using the ui-dropdown component with the onChange action.

    Parse error on line 14:
    ...n class="selection" onChange(action 'upd
    -----------------------^
    Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'

Posting my Ember info below because I'm thinking it's probably a version thing

    Ember Inspector 1.9.3
    Ember 1.13.7
    Ember Data 1.13.9
    jQuery 1.11.3
    Ember Simple Auth 0.8.0
    Ember Simple Auth Torii 0.8.0

**Comment by kmmathis** [comment]
FWIW, I'm trying to use the dropdown component to update a property on a model.

**Comment by aaronbhansen** [comment]
I know there are some block issues that were fixed after ember 1.13.7, can you update to the latest to check. Also can you paste a code block around the dropdown, there isn't enough context to know what going on. Thanks

**Comment by kmmathis** [comment]
I've been delaying upgrading to Ember 2.0 because of Ember Simple Auth issues, but I can take a look at  that again and see if I can get to 2.0.

Here is the whole template file

    {{#if model}}    

    <table class="ui fixed single line celled table">
      <thead>
        <tr>
          <th>Category</th>
          <th>Name</th>
        </tr>
      </thead>
      <tbody>
        {{#each model as |lead|}}
          <tr data-lead-category="{{lead.category}}">
            <td class="overflowable">
              {{#ui-dropdown class="selection" }}
                <div class="default text">{{lead.category}}</div>
                <i class="dropdown icon"></i>
                <div class="menu">
                {{#each leadCategories as |category|}}
                  <div class="item" data-id="{{category}}">
                    {{category}}
                  </div>
                {{/each}}
                </div>
              {{/ui-dropdown}}
            </td>
            <td>{{lead.fullname}}</td>
          </tr>
        {{/each}}
      </tbody>
    </table>    

    {{else}}    

      <p>No Leads</p>    

    {{/if}}

**Comment by aaronbhansen** [comment]
Right i'm just meant ember 1.13.10 I believe is the latest and yours showed 1.13.7

**Comment by kmmathis** [comment]
Updating to 1.13.10 doesn't seem to fix it. Getting the same build error.

**Comment by kmmathis** [comment]
I'm going to set up an Ember 2.0 project and see if the dropdown component is working there.

**Comment by kmmathis** [comment]
Running Ember 2.0 gets the same build error.

**Comment by Balougahfitz** [comment]
This just looks like a syntax error; you need to specify your 'onChange' event with a equal sign, thusly:

    onChange=(action 'update')

**Comment by kmmathis** [comment]
Ah! Thanks for catching that. It makes a lot more sense with the equal sign now :)
